# Triggers when someone pushes to the main branch or if someone makes a pull request and merges it to main branch
on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# Functions
jobs:

  # Build Job
  build:

    # Name of job
    name: Build

    # The OS to run the job on
    runs-on: ubuntu-latest
    
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      
      - name: Install NPM Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
      
      - name: Upload artifical in order to deploy
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  # Deploy Job
  deploy:
    name: Build
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GORDAN }}
          publish_dir: ./dist